package com.td.enrich.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;

/**
 * Database row that records every enrichment request and its outcome.
 *
 * <p>Every call to {@code POST /api/v1/enrich} creates one of these rows. The row
 * starts with {@code status = PENDING} and is updated to {@code SUCCESS} or
 * {@code FAILED} once processing completes. This gives us a full audit trail —
 * we can always look up what was requested, what Plaid returned, and whether it
 * succeeded.
 *
 * <p><b>Why we store JSON strings instead of relational columns:</b>
 * The request and response shapes can vary (different numbers of transactions,
 * optional fields). Storing them as JSON keeps the schema simple while still
 * allowing the data to be retrieved and replayed if needed.
 *
 * <p>Lombok annotations used here:
 * <ul>
 *   <li>{@code @Data} — generates getters, setters, equals, hashCode, and toString.</li>
 *   <li>{@code @Builder} — lets callers use a fluent builder:
 *       {@code EnrichmentEntity.builder().requestId("...").build()}.</li>
 *   <li>{@code @NoArgsConstructor} / {@code @AllArgsConstructor} — required by JPA
 *       (JPA needs a no-arg constructor to instantiate entities when reading from the DB).</li>
 * </ul>
 */
@Entity
@Table(name = "enrichment_records",
       indexes = {
           // Speeds up queries that filter or sort by time (e.g. finding recent requests)
           @Index(name = "idx_enrichment_created_at", columnList = "created_at"),
           // Speeds up queries that filter by status (e.g. finding all FAILED records)
           @Index(name = "idx_enrichment_status", columnList = "status"),
           // Composite index for queries that filter by both time and status
           @Index(name = "idx_enrichment_created_status", columnList = "created_at,status")
       })
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EnrichmentEntity {

    /**
     * The UUID generated by {@link com.td.enrich.util.GuidGenerator} for this request.
     * Serves as the primary key and is returned to clients so they can poll for results.
     */
    @Id
    @Column(name = "request_id", nullable = false, length = 36)
    private String requestId;

    /**
     * The original client request serialized as JSON. Stored so we can:
     * <ol>
     *   <li>Reconstruct the enriched response on a subsequent {@code GET /{requestId}} call
     *       by re-running the cache lookup with the original (description, merchantName) pairs.</li>
     *   <li>Replay the request if something went wrong.</li>
     * </ol>
     */
    @Column(name = "original_request", nullable = false, columnDefinition = "NVARCHAR(MAX)")
    private String originalRequest;

    /**
     * The raw Plaid API response serialized as JSON, set when enrichment succeeds.
     * {@code null} when status is {@code PENDING} or {@code FAILED}.
     */
    @Column(name = "plaid_response", columnDefinition = "NVARCHAR(MAX)")
    private String plaidResponse;

    /**
     * UTC timestamp set when this record is first written to the database.
     * The {@code @Builder.Default} ensures the builder also initializes this field
     * (without it, Lombok's builder would leave it null).
     */
    @Column(name = "created_at", nullable = false)
    @Builder.Default
    private OffsetDateTime createdAt = OffsetDateTime.now();

    /**
     * UTC timestamp updated every time this record is modified.
     * JPA calls {@link #onUpdate()} automatically to refresh this value.
     */
    @Column(name = "updated_at", nullable = false)
    @Builder.Default
    private OffsetDateTime updatedAt = OffsetDateTime.now();

    /**
     * The processing outcome: {@code PENDING}, {@code SUCCESS}, or {@code FAILED}.
     * <ul>
     *   <li>{@code PENDING} — request received; enrichment not yet attempted.</li>
     *   <li>{@code SUCCESS} — Plaid returned data; merchant cache populated.</li>
     *   <li>{@code FAILED} — an error occurred; see {@link #errorMessage}.</li>
     * </ul>
     */
    @Column(name = "status", nullable = false, length = 20)
    private String status;

    /**
     * Set when {@code status = FAILED}. Contains a human-readable description of
     * what went wrong (e.g. "Server error from Plaid API: 503"). {@code null} on success.
     */
    @Column(name = "error_message", length = 500)
    private String errorMessage;

    /**
     * JPA lifecycle callback — runs automatically just before an UPDATE SQL statement.
     * Keeps {@code updatedAt} current without callers having to remember to set it.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }

    /**
     * JPA lifecycle callback — runs automatically just before an INSERT SQL statement.
     * Guards against a null {@code createdAt} / {@code updatedAt} in case the entity
     * was constructed without the builder (e.g. in unit tests that use {@code new}).
     */
    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = OffsetDateTime.now();
        }
        if (this.updatedAt == null) {
            this.updatedAt = OffsetDateTime.now();
        }
    }
}
