package com.td.enrich.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;

/**
 * The response returned to the client after their transactions have been enriched.
 *
 * <p>Every enrichment call — whether it hits the cache or calls Plaid live —
 * produces one of these objects. The {@code status} field tells the caller whether
 * enrichment succeeded:
 * <ul>
 *   <li>{@code SUCCESS} — all transactions were enriched and {@code enrichedTransactions}
 *       is populated.</li>
 *   <li>{@code FAILED} — an unrecoverable error occurred; {@code errorMessage}
 *       explains why and {@code enrichedTransactions} will be empty.</li>
 *   <li>{@code PROCESSING} — used only for async batch polling; enrichment is still
 *       in progress.</li>
 * </ul>
 *
 * <p>Example JSON response:
 * <pre>{@code
 * {
 *   "requestId": "550e8400-e29b-41d4-a716-446655440000",
 *   "enrichedTransactions": [
 *     {
 *       "transactionId": "txn_001",
 *       "merchantId":    "merchant-starbucks-seattle",
 *       "category":      "Coffee Shops",
 *       "merchantName":  "Starbucks Coffee",
 *       "logoUrl":       "https://logo.clearbit.com/starbucks.com",
 *       "metadata": { "confidenceLevel": "HIGH", "website": "https://starbucks.com" }
 *     }
 *   ],
 *   "processedAt":  "2026-04-07T15:30:15.123+00:00",
 *   "status":       "SUCCESS",
 *   "errorMessage": null
 * }
 * }</pre>
 */
@Schema(description = "Response containing enriched transaction data from Plaid")
public record EnrichmentResponse(

    /**
     * A UUID generated by this service to uniquely identify the enrichment request.
     * Clients can use this ID to look up results via {@code GET /api/v1/enrich/{requestId}}.
     */
    @Schema(description = "Service-generated UUID for this request",
            example = "550e8400-e29b-41d4-a716-446655440000")
    String requestId,

    /**
     * The list of enriched transactions, one entry per input transaction.
     * Empty ({@code []}) when {@code status} is {@code FAILED} or {@code PROCESSING}.
     */
    @Schema(description = "Enriched transactions — empty if status is FAILED or PROCESSING")
    List<EnrichedTransaction> enrichedTransactions,

    /**
     * The UTC timestamp at which enrichment completed. {@code null} when
     * {@code status} is {@code PROCESSING} because work hasn't finished yet.
     */
    @Schema(description = "UTC timestamp when enrichment completed — null while PROCESSING")
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX")
    OffsetDateTime processedAt,

    /**
     * Overall result of the enrichment operation.
     * One of {@code SUCCESS}, {@code FAILED}, or {@code PROCESSING}.
     */
    @Schema(description = "Enrichment result: SUCCESS | FAILED | PROCESSING", example = "SUCCESS")
    String status,

    /**
     * Human-readable explanation set when {@code status} is {@code FAILED}.
     * {@code null} on success.
     */
    @Schema(description = "Error description when status is FAILED — null on success",
            nullable = true)
    String errorMessage

) {

    /**
     * Convenience constructor for successful responses that have no error message.
     * Delegates to the full constructor with {@code errorMessage = null}.
     *
     * @param requestId            the generated request UUID
     * @param enrichedTransactions the enriched transaction data
     * @param processedAt          the completion timestamp
     * @param status               "SUCCESS" (or any non-error status string)
     */
    public EnrichmentResponse(String requestId,
                               List<EnrichedTransaction> enrichedTransactions,
                               OffsetDateTime processedAt,
                               String status) {
        this(requestId, enrichedTransactions, processedAt, status, null);
    }

    /**
     * One enriched transaction — a single row from the original request, augmented
     * with merchant data retrieved from Plaid (via the cache or a live API call).
     *
     * <p>The {@code merchantId} is a stable UUID generated by this service the first
     * time a given (description, merchantName) pair is encountered. Subsequent requests
     * for the same merchant always return the same {@code merchantId}, making it safe
     * to use as a foreign key in downstream systems.
     */
    @Schema(description = "A single transaction enriched with Plaid merchant data")
    public record EnrichedTransaction(

        /**
         * The transaction identifier echoed from the Plaid response.
         * Used by callers to correlate each enriched result with the original input row.
         */
        @Schema(description = "Transaction ID from the Plaid response", example = "txn_001")
        String transactionId,

        /**
         * A stable UUID assigned by this service to the merchant identified by the
         * (description, merchantName) cache key. The same merchant always receives
         * the same ID, even across restarts.
         */
        @Schema(description = "Stable service-generated UUID for this merchant",
                example = "550e8400-e29b-41d4-a716-446655440001")
        String merchantId,

        /**
         * The human-readable merchant category returned by Plaid
         * (e.g. "Coffee Shops", "Grocery Stores").
         */
        @Schema(description = "Plaid merchant category", example = "Coffee Shops")
        String category,

        /**
         * The standardized merchant name as Plaid knows it
         * (e.g. "Starbucks Coffee" rather than the raw "STARBUCKS #1234 SEATTLE WA").
         */
        @Schema(description = "Standardized merchant name from Plaid", example = "Starbucks Coffee")
        String merchantName,

        /**
         * URL to the merchant's logo image, or {@code null} if Plaid doesn't have one.
         * Safe to display directly in a UI.
         */
        @Schema(description = "Merchant logo URL — null if unavailable",
                example = "https://logo.clearbit.com/starbucks.com", nullable = true)
        String logoUrl,

        /**
         * A map of additional Plaid metadata. Common keys include:
         * <ul>
         *   <li>{@code confidenceLevel} — "HIGH", "MEDIUM", or "LOW"</li>
         *   <li>{@code categoryId} — Plaid's numeric category code</li>
         *   <li>{@code website} — merchant's website URL</li>
         * </ul>
         */
        @Schema(description = "Additional Plaid metadata (confidence, category code, website, etc.)")
        Map<String, Object> metadata

    ) {}
}
