package com.plaid.enrich.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;

/**
 * JPA Entity for persisting enrichment request/response pairs.
 * Stores the GUID, original request, and Plaid response for auditing and retrieval.
 */
@Entity
@Table(name = "enrichment_records",
       indexes = {
           @Index(name = "idx_enrichment_created_at", columnList = "created_at"),
           @Index(name = "idx_enrichment_status", columnList = "status"),
           @Index(name = "idx_enrichment_created_status", columnList = "created_at,status")
       })
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EnrichmentEntity {

    /**
     * GUID generated by the service to uniquely identify this enrichment request.
     */
    @Id
    @Column(name = "request_id", nullable = false, length = 36)
    private String requestId;

    /**
     * JSON representation of the original client request.
     * Stored for audit trail and potential replay.
     */
    @Column(name = "original_request", nullable = false, columnDefinition = "NVARCHAR(MAX)")
    private String originalRequest;

    /**
     * JSON representation of the Plaid API response.
     * Linked to the original request via requestId.
     */
    @Column(name = "plaid_response", columnDefinition = "NVARCHAR(MAX)")
    private String plaidResponse;

    /**
     * Timestamp when the record was created.
     */
    @Column(name = "created_at", nullable = false)
    @Builder.Default
    private OffsetDateTime createdAt = OffsetDateTime.now();

    /**
     * Timestamp when the record was last updated.
     */
    @Column(name = "updated_at", nullable = false)
    @Builder.Default
    private OffsetDateTime updatedAt = OffsetDateTime.now();

    /**
     * Processing status: SUCCESS, FAILED, PENDING.
     */
    @Column(name = "status", nullable = false, length = 20)
    private String status;

    /**
     * Error message if the processing failed.
     */
    @Column(name = "error_message", length = 500)
    private String errorMessage;

    /**
     * JPA lifecycle callback to update the updatedAt timestamp.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }

    /**
     * JPA lifecycle callback to set createdAt and updatedAt on persist.
     */
    @PrePersist
    protected void onCreate() {
        if (this.createdAt == null) {
            this.createdAt = OffsetDateTime.now();
        }
        if (this.updatedAt == null) {
            this.updatedAt = OffsetDateTime.now();
        }
    }
}
