package com.plaid.enrich.domain;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;

/**
 * JPA Entity for caching merchant enrichment data keyed on (description, merchantName).
 * Each unique (description, merchantName) pair is assigned a stable merchantId UUID.
 */
@Entity
@Table(
    name = "merchant_cache",
    uniqueConstraints = @UniqueConstraint(
        name = "UQ_merchant_desc_name",
        columnNames = {"description", "merchant_name"}
    )
)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MerchantCacheEntity {

    /**
     * Stable UUID for this (description, merchantName) pair, generated by GuidGenerator.
     */
    @Id
    @Column(name = "merchant_id", nullable = false, length = 36)
    private String merchantId;

    /**
     * Transaction description used as part of the cache key.
     */
    @Column(name = "description", nullable = false, columnDefinition = "NVARCHAR(500)")
    private String description;

    /**
     * Merchant name used as part of the cache key. Null is coerced to empty string.
     */
    @Column(name = "merchant_name", nullable = false, columnDefinition = "NVARCHAR(255)")
    private String merchantName;

    /**
     * JSON of PlaidEnrichedTransaction stored from the Plaid API response.
     */
    @Column(name = "plaid_response", columnDefinition = "NVARCHAR(MAX)")
    private String plaidResponse;

    /**
     * Timestamp when this cache entry was created.
     */
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;
}
