-- Plaid Enrich Service - Initial Schema
-- Creates the enrichment_records table for persisting requests and responses

CREATE TABLE enrichment_records (
    request_id VARCHAR(36) NOT NULL,
    original_request NVARCHAR(MAX) NOT NULL,
    plaid_response NVARCHAR(MAX),
    created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    updated_at DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    status VARCHAR(20) NOT NULL,
    error_message NVARCHAR(500),

    CONSTRAINT PK_enrichment_records PRIMARY KEY (request_id)
);

-- Indexes for performance
CREATE INDEX idx_enrichment_created_at ON enrichment_records(created_at DESC);
CREATE INDEX idx_enrichment_status ON enrichment_records(status);
CREATE INDEX idx_enrichment_created_status ON enrichment_records(created_at DESC, status);

-- Comments for documentation
EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'Stores enrichment request/response pairs with GUID linking',
    @level0type = N'SCHEMA', @level0name = N'dbo',
    @level1type = N'TABLE',  @level1name = N'enrichment_records';

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'GUID generated by service to uniquely identify each enrichment request',
    @level0type = N'SCHEMA', @level0name = N'dbo',
    @level1type = N'TABLE',  @level1name = N'enrichment_records',
    @level2type = N'COLUMN', @level2name = N'request_id';

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'JSON representation of the original client request',
    @level0type = N'SCHEMA', @level0name = N'dbo',
    @level1type = N'TABLE',  @level1name = N'enrichment_records',
    @level2type = N'COLUMN', @level2name = N'original_request';

EXEC sp_addextendedproperty
    @name = N'MS_Description',
    @value = N'JSON representation of the Plaid API response',
    @level0type = N'SCHEMA', @level0name = N'dbo',
    @level1type = N'TABLE',  @level1name = N'enrichment_records',
    @level2type = N'COLUMN', @level2name = N'plaid_response';
